export const tshirts = [
	{
		name: 'Product 1',
		image: 'tshirt.svg',
		description: 'This is the description of Product 1.',
		rating: 4.5,
		numberOfRating: 10,
		price: 19.99,
		discount: 10,
	},
	{
		name: 'Product 2',
		image: 'tshirt.svg',
		description: 'This is the description of Product 2.',
		rating: 4.2,
		numberOfRating: 8,
		price: 29.99,
		discount: 20,
	},
	{
		name: 'Product 3',
		image: 'tshirt.svg',
		description: 'This is the description of Product 3.',
		rating: 4.7,
		numberOfRating: 15,
		price: 39.99,
		discount: 15,
	},
	{
		name: 'Product 4',
		image: 'tshirt.svg',
		description: 'This is the description of Product 4.',
		rating: 4.0,
		numberOfRating: 6,
		price: 49.99,
		discount: 25,
	},
];

export const cardsmen = [
	{
		image: '/images/imagem1.png',
		title: 'T-shirts',
	},

	{
		image: '/images/imagem2.png',
		title: 'Formal Shirts',
	},
	{
		image: '/images/imagem3.png',
		title: 'Casual Trousers',
	},
	{
		image: '/images/imagem4.png',
		title: 'Jeans',
	},
	{
		image: '/images/imagem5.png',
		title: 'Casual shirts',
	},

	{
		image: '/images/imagem6.png',
		title: 'Shorts & 3/4th',
	},

	// Add more cards as needed
];

export const semiformaltshirts = [
	{
		name: 'Product 1',
		image: '/images/clothing/MShirt.svg',
		description: 'This is the description of Product 1.',
		rating: 4.5,
		numberOfRating: 10,
		price: 19.99,
		discount: 10,
	},
	{
		name: 'Product 2',
		image: '/images/clothing/MShirt.svg',
		description: 'This is the description of Product 2.',
		rating: 4.2,
		numberOfRating: 8,
		price: 29.99,
		discount: 20,
	},
	{
		name: 'Product 3',
		image: '/images/clothing/MShirt.svg',
		description: 'This is the description of Product 3.',
		rating: 4.7,
		numberOfRating: 15,
		price: 39.99,
		discount: 15,
	},
	{
		name: 'Product 4',
		image: '/images/clothing/MShirt.svg',
		description: 'This is the description of Product 4.',
		rating: 4.0,
		numberOfRating: 6,
		price: 49.99,
		discount: 25,
	},
];

export const pants = [
	{
		name: 'Product 1',
		image: 'menpants.jpeg',
		description: 'This is the description of Product 1.',
		rating: 4.5,
		numberOfRating: 10,
		price: 19.99,
		discount: 10,
	},
	{
		name: 'Product 2',
		image: 'menpants.jpeg',
		description: 'This is the description of Product 2.',
		rating: 4.2,
		numberOfRating: 8,
		price: 29.99,
		discount: 20,
	},
	{
		name: 'Product 3',
		image: 'menpants.jpeg',
		description: 'This is the description of Product 3.',
		rating: 4.7,
		numberOfRating: 15,
		price: 39.99,
		discount: 15,
	},
	{
		name: 'Product 4',
		image: 'menpants.jpeg',
		description: 'This is the description of Product 4.',
		rating: 4.0,
		numberOfRating: 6,
		price: 49.99,
		discount: 25,
	},
];

export const suits = [
	{
		name: 'Product 1',
		image: 'mensuit.jpeg',
		description: 'This is the description of Product 1.',
		rating: 4.5,
		numberOfRating: 10,
		price: 19.99,
		discount: 10,
	},
	{
		name: 'Product 2',
		image: 'mensuit.jpeg',
		description: 'This is the description of Product 2.',
		rating: 4.2,
		numberOfRating: 8,
		price: 29.99,
		discount: 20,
	},
	{
		name: 'Product 3',
		image: 'mensuit.jpeg',
		description: 'This is the description of Product 3.',
		rating: 4.7,
		numberOfRating: 15,
		price: 39.99,
		discount: 15,
	},
	{
		name: 'Product 4',
		image: 'mensuit.jpeg',
		description: 'This is the description of Product 4.',
		rating: 4.0,
		numberOfRating: 6,
		price: 49.99,
		discount: 25,
	},
];

export const sampleProducts = [
	{
		productName: 'Product 5',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 5.',
		rating: 4.8,
		numberOfRating: 12,
		price: 59.99,
		discount: 10,
	},

	{
		productName: 'Product 6',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 6.',
		rating: 4.5,
		numberOfRating: 18,
		price: 69.99,
		discount: 15,
	},

	{
		productName: 'Product 7',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 7.',
		rating: 4.2,
		numberOfRating: 9,
		price: 79.99,
		discount: 20,
	},

	{
		productName: 'Product 8',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 8.',
		rating: 4.9,
		numberOfRating: 22,
		price: 89.99,
		discount: 10,
	},

	{
		productName: 'Product 9',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 9.',
		rating: 4.3,
		numberOfRating: 14,
		price: 99.99,
		discount: 25,
	},

	{
		productName: 'Product 10',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 10.',
		rating: 4.7,
		numberOfRating: 20,
		price: 109.99,
		discount: 15,
	},

	{
		productName: 'Product 11',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 11.',
		rating: 4.1,
		numberOfRating: 8,
		price: 119.99,
		discount: 10,
	},

	{
		productName: 'Product 12',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 12.',
		rating: 4.6,
		numberOfRating: 16,
		price: 129.99,
		discount: 20,
	},

	{
		productName: 'Product 13',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 13.',
		rating: 4.4,
		numberOfRating: 10,
		price: 139.99,
		discount: 15,
	},

	{
		productName: 'Product 14',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 14.',
		rating: 4.8,
		numberOfRating: 25,
		price: 149.99,
		discount: 10,
	},

	{
		productName: 'Product 15',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 15.',
		rating: 4.2,
		numberOfRating: 12,
		price: 159.99,
		discount: 20,
	},

	{
		productName: 'Product 16',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 16.',
		rating: 4.9,
		numberOfRating: 18,
		price: 169.99,
		discount: 10,
	},

	{
		productName: 'Product 17',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 17.',
		rating: 4.3,
		numberOfRating: 22,
		price: 179.99,
		discount: 15,
	},

	{
		productName: 'Product 18',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 18.',
		rating: 4.7,
		numberOfRating: 14,
		price: 189.99,
		discount: 10,
	},

	{
		productName: 'Product 19',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 19.',
		rating: 4.0,
		numberOfRating: 20,
		price: 199.99,
		discount: 25,
	},

	{
		productName: 'Product 20',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 20.',
		rating: 4.6,
		numberOfRating: 8,
		price: 209.99,
		discount: 15,
	},

	{
		productName: 'Product 21',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 21.',
		rating: 4.4,
		numberOfRating: 16,
		price: 219.99,
		discount: 20,
	},

	{
		productName: 'Product 22',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 22.',
		rating: 4.8,
		numberOfRating: 10,
		price: 229.99,
		discount: 10,
	},

	{
		productName: 'Product 23',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 23.',
		rating: 4.2,
		numberOfRating: 25,
		price: 239.99,
		discount: 15,
	},

	{
		productName: 'Product 24',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 24.',
		rating: 4.7,
		numberOfRating: 12,
		price: 249.99,
		discount: 10,
	},

	{
		productName: 'Product 25',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 25.',
		rating: 4.1,
		numberOfRating: 18,
		price: 259.99,
		discount: 20,
	},

	{
		productName: 'Product 26',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 26.',
		rating: 4.6,
		numberOfRating: 22,
		price: 269.99,
		discount: 10,
	},
	{
		productName: 'Product 1',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 1.',
		rating: 4.5,
		numberOfRating: 10,
		price: 19.99,
		discount: 10,
	},
	{
		productName: 'Product 2',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 2.',
		rating: 4.2,
		numberOfRating: 8,
		price: 29.99,
		discount: 20,
	},
	{
		productName: 'Product 3',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 3.',
		rating: 4.7,
		numberOfRating: 15,
		price: 39.99,
		discount: 15,
	},
	{
		productName: 'Product 4',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 4.',
		rating: 4.0,
		numberOfRating: 6,
		price: 49.99,
		discount: 25,
	},
	{
		productName: 'Product 1',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 1.',
		rating: 4.5,
		numberOfRating: 10,
		price: 19.99,
		discount: 10,
	},
	{
		productName: 'Product 2',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 2.',
		rating: 4.2,
		numberOfRating: 8,
		price: 29.99,
		discount: 20,
	},
	{
		productName: 'Product 3',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 3.',
		rating: 4.7,
		numberOfRating: 15,
		price: 39.99,
		discount: 15,
	},
	{
		productName: 'Product 4',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 4.',
		rating: 4.0,
		numberOfRating: 6,
		price: 49.99,
		discount: 25,
	},
	{
		productName: 'Product 27',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 27.',
		rating: 4.3,
		numberOfRating: 14,
		price: 279.99,
		discount: 15,
	},
	{
		productName: 'Product 28',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 28.',
		rating: 4.7,
		numberOfRating: 20,
		price: 289.99,
		discount: 10,
	},
	{
		productName: 'Product 29',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 29.',
		rating: 4.1,
		numberOfRating: 8,
		price: 299.99,
		discount: 20,
	},
	{
		productName: 'Product 30',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 30.',
		rating: 4.6,
		numberOfRating: 16,
		price: 309.99,
		discount: 15,
	},
	{
		productName: 'Product 31',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 31.',
		rating: 4.4,
		numberOfRating: 10,
		price: 319.99,
		discount: 10,
	},
	{
		productName: 'Product 32',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 32.',
		rating: 4.8,
		numberOfRating: 25,
		price: 329.99,
		discount: 15,
	},
	{
		productName: 'Product 33',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 33.',
		rating: 4.2,
		numberOfRating: 12,
		price: 339.99,
		discount: 20,
	},
	{
		productName: 'Product 34',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 34.',
		rating: 4.7,
		numberOfRating: 18,
		price: 349.99,
		discount: 10,
	},
	{
		productName: 'Product 35',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 35.',
		rating: 4.1,
		numberOfRating: 22,
		price: 359.99,
		discount: 15,
	},
	{
		productName: 'Product 36',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 36.',
		rating: 4.6,
		numberOfRating: 14,
		price: 369.99,
		discount: 20,
	},
	{
		productName: 'Product 37',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 37.',
		rating: 4.3,
		numberOfRating: 10,
		price: 379.99,
		discount: 10,
	},
	{
		productName: 'Product 38',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 38.',
		rating: 4.9,
		numberOfRating: 20,
		price: 389.99,
		discount: 15,
	},
	{
		productName: 'Product 39',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 39.',
		rating: 4.5,
		numberOfRating: 12,
		price: 399.99,
		discount: 10,
	},
	{
		productName: 'Product 40',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 40.',
		rating: 4.0,
		numberOfRating: 18,
		price: 409.99,
		discount: 25,
	},
	{
		productName: 'Product 41',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 41.',
		rating: 4.6,
		numberOfRating: 22,
		price: 419.99,
		discount: 15,
	},
	{
		productName: 'Product 42',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 42.',
		rating: 4.2,
		numberOfRating: 14,
		price: 429.99,
		discount: 20,
	},
	{
		productName: 'Product 43',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 43.',
		rating: 4.8,
		numberOfRating: 10,
		price: 439.99,
		discount: 10,
	},
	{
		productName: 'Product 44',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 44.',
		rating: 4.4,
		numberOfRating: 25,
		price: 449.99,
		discount: 15,
	},
	{
		productName: 'Product 45',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 45.',
		rating: 4.9,
		numberOfRating: 12,
		price: 459.99,
		discount: 10,
	},
	{
		productName: 'Product 46',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 46.',
		rating: 4.3,
		numberOfRating: 18,
		price: 469.99,
		discount: 20,
	},
	{
		productName: 'Product 47',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 47.',
		rating: 4.7,
		numberOfRating: 22,
		price: 479.99,
		discount: 10,
	},
	{
		productName: 'Product 48',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 48.',
		rating: 4.2,
		numberOfRating: 14,
		price: 489.99,
		discount: 15,
	},
	{
		productName: 'Product 49',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 49.',
		rating: 4.6,
		numberOfRating: 10,
		price: 499.99,
		discount: 20,
	},
	{
		productName: 'Product 50',
		image: '/images/clothing/MShirt.svg',
		fullDescription: 'This is the description of Product 50.',
		rating: 4.0,
		numberOfRating: 18,
		price: 509.99,
		discount: 25,
	},
];
